### ISSUE TITLE
Possibility to send NULL in POST request.

### ISSUE THREAD

**Issue by kessko** [canton7/RestEase#109]
Hey there, I’m using RestEase Version="1.4.7" for net core application.
I faced with interesting issue.
I have a simple interface:

```
    public interface IPing
    {
        [Post("/api/ping")]
        IEnumerable<string> Ping([Body] List<string> list);
    }
```

And the endpoint looks like: 
```
    [HttpPost]
    public IEnumerable<string> Ping([FromBody]List<string> list)
    {
        return list;
    }
```
The interesting thing is - if I decided to call this method without passing list, I mean I pass null.
My request: 

```
POST https://localhost:5001/api/ping HTTP/1.1
User-Agent: HTTP-REPL
Content-Length: 0
Host: localhost:5001
```
And i see exception:
`RestEase.ApiException: 'POST "http://localhost:33330/api/ping" failed because response status code does not indicate success: 415 (Unsupported Media Type).'`

That’s fair, I didn’t set Content-Type header. I fixed this by updating interface.

```
    public interface IPing
    {
        [Post("/api/ping")]
        [Header("Content-Type", "application/json")]
        IEnumerable<string> Ping([Body] List<string> list);
    }
```
But now I’m getting another exception:
`System.ArgumentException: 'Header Content-Type could not be added. Maybe it's a content-related header but there's no content, or it's associated with HTTP responses, or it's malformed?'`

I’m sure on 100% that if I set header everything will be ok. This request will pass correctly:
```
POST http://localhost:33330/api/ping HTTP/1.1
User-Agent: HTTP-REPL
Content-Length: 0
Content-Type: application/json
Host: localhost:33330
```

Any ideas or workaround how should i set header when request have no content?

**Comment by canton7** [comment]
Right, so we spot that you passed `null` for the body, and so don't set HttpRequestMessage.Content [here](https://github.com/canton7/RestEase/blob/9676401f6bf2882e747803e361221b5444d05c46/src/RestEase/Implementation/Requester.cs#L275). Then when we come to apply headers [here](https://github.com/canton7/RestEase/blob/9676401f6bf2882e747803e361221b5444d05c46/src/RestEase/Implementation/Requester.cs#L314), we fail to it to the request content because there is no request content [here](https://github.com/canton7/RestEase/blob/9676401f6bf2882e747803e361221b5444d05c46/src/RestEase/Implementation/Requester.cs#L342).

I think there's an argument to say that we should add an empty body if you use `[Body]` but pass null (however I'm not sure whether this would break anything...). 

As a short-term workaround, define another method which takes a `[Body] string` and pass `string.Empty` to it.

**Comment by kessko** [comment]
I’m not sure that I understand how it will helps me.
I need to call `api/ping` without `list` parameter because it’s a business logic of endpoint.

If you sent me `list` – I will use it to sort(for example) If not, I will give you all that I have. 

How new method with `[Body] string`  will help me?

**Comment by canton7** [comment]
I'm giving you a workaround which should work until we can decide on the right changes, if any, to make to RestEase.

```csharp
public interface IPing
{
    [Post("/api/ping")]
    IEnumerable<string> Ping([Body] List<string> list);

    [Post("/api/ping")]
    [Header("Content-Type", "application/json")]
    IEnumerable<string> Ping([Body] string filter);
}
```

Instead of doing this:

```csharp
api.Ping(null);
```

Do this:

```csharp
api.Ping(string.Empty);
```

In order to make RestEase send an empty body, which can still have a Content-Type header on it,

**Comment by kessko** [comment]
Oh i see. To be honest right now in client code i'm doing this:

`api.Ping(list ?? new List<string>());`

But your advice also works, thank you.

Howewer, usually we cannot control client code and imho this should be fixed.

Thank you ones again for so quick response.

**Comment by canton7** [comment]
Right, so you're sending the body `[]` (with a Content-Length of 2), instead of sending an empty body. That to me makes more sense - you're actually sending a body, so it makes sense to put a Content-Type header on it.

I think it's incorrect to say that an empty body is application/json, since an empty string is *not* valid JSON. Nor would it be correct to say that an empty body is application/xml, since an empty string is again not valid XML. However an empty body would be a valid text/plain content.... But I think putting this sort of logic into RestEase is several steps too far in the wrong direction.

So I think the sensible choices are: 
1. If they've added a Header to the method, and the method has a body which is null, add an empty body
2. If they've added a header to either the method or the interface, and a method has a body which is null, add an empty body

**Comment by kessko** [comment]
Totally agree, and as another argument here i want to show behavior of native HttpClient:

```
     var client = new HttpClient();
     client.BaseAddress = new Uri("http://localhost:33330");
     client.DefaultRequestHeaders.TryAddWithoutValidation("Content-Type", "application/json");

     var message = await client
                       .PostAsync<List<string>>("api/ping", null, new JsonMediaTypeFormatter());
     var result = await message.Content.ReadAsAsync<string>();
```

This code will sent:
```
POST http://localhost:33330/api/ping HTTP/1.1
Content-Type: application/json; charset=utf-8
Host: localhost:33330
Content-Length: 4

null
```

**Comment by canton7** [comment]
Well that's sending the literal string "null", not an empty body. See how the content length is 4, not 0.

**Comment by canton7** [comment]
HttpClient, of course, *doesn't* let you add content-related headers if there's no content. That's the root cause of this issue in RestEase!

**Comment by kessko** [comment]
Look at this please #110

**Comment by canton7** [comment]
Please see my earlier message:

> So I think the sensible choices are:
>
>    If they've added a Header to the method, and the method has a body which is null, add an empty body
>    If they've added a header to either the method or the interface, and a method has a body which is null, add an empty body

I still think one of those choices is the right decision. I still think we should decide on one of those choices. I will reject PRs which do not implement one of those choices.

**Comment by kessko** [comment]
What about this?
https://github.com/canton7/RestEase/pull/110#discussion_r234686127

**Comment by kessko** [comment]
After our conversation in PR comments, if i understand you right then acceptable fix should be [here ](https://github.com/canton7/RestEase/blob/9676401f6bf2882e747803e361221b5444d05c46/src/RestEase/Implementation/Requester.cs#L275). 
Sounds like - if ObjectValue is null but the headers are added, and only if there are headers on the method (not the class) - then returns empty content instead of null.
and looks like:

```
  protected virtual HttpContent ConstructContent(IRequestInfo requestInfo)
  {
      if (requestInfo.BodyParameterInfo == null )
          return null;

      if (requestInfo.BodyParameterInfo.ObjectValue == null && requestInfo.MethodHeaders.Any())
          return new ByteArrayContent(new byte[0]);
      // other if statements...
```
Unfortunately it is not possible to use Array.Empty<> in net45 and netstandard 1.1

![screenshot_12](https://user-images.githubusercontent.com/11807113/48761537-ed59f280-ecb9-11e8-99f8-2bd66e7b7cb6.png)

I will change behavior of existing test that will be  [broken ](https://github.com/canton7/RestEase/blob/9676401f6bf2882e747803e361221b5444d05c46/src/RestEaseUnitTests/RequesterTests/ContentConstructionTests.cs#L31), tests that cover new logic also will be added.
 
@canton7  anything else that i missed?

**Comment by canton7** [comment]
Actually, my [last thought](https://github.com/canton7/RestEase/pull/110#issuecomment-439984093) is that it should be added where the headers are added, and only if there are body-related headers on the method itself (not the class). That way we avoid instantiating an empty body in most cases.

**Comment by kessko** [comment]
I see, those changes definitely should fix the issue.

May I assume your branch will be merged in master after you finished with tests?
If you need any help here, just tell me.

**Comment by canton7** [comment]
Sorry, this slipped under my radar. Including this in the next release shortly.
