### ISSUE TITLE
Feature proposal: [BasePath] attribute

### ISSUE THREAD

**Issue by mansellan** [canton7/RestEase#113]
The routing attributes in RestEase serve a similar function to those of ASP.Net MVC. In the latter, it's possible to put a `Route[]` attribute on the interface, which then gets prepended to the routes of all its service operations.

It would be helpful if RestEase offered a similar attribute (possibly `BasePath`?) for interfaces. I realise that the entire base URL can be specified when creating the client, but sometimes it's not practical to put paths in this URI - for example where the host address comes from configuration and hosts multiple endpoints.

Happy to contribute a PR if this is considered in-scope.

**Comment by canton7** [comment]
I'd say that's in scope - needs a little bit of thought though:

1. It should work with path properties
1. How does it interact with someone setting a path on the HttpClient? Which one wins?
1. Presumably we need to support someone setting a base path on the HttpClient, then part of a path on the interface, and the rest of it in the method? So this new attribute supports both absolute and relative paths.

**Comment by mansellan** [comment]
How about:

1. Agreed, but this shouldn't be a problem, as:
- if the method path is absolute, it wins (current behaviour)
- if the method path is relative, it (including any path properties) will be prepended by the `BasePath` (if present)
2. If the `BasePath` property is absolute, it should win and the HttpClient path be ignored - this would be consistent with the current behaviour of absolute method paths.
3. Yes - if the `BasePath` property is relative, it should go between the HttpClient path and the method path (in fact this is the use-case I need atm)

**Comment by canton7** [comment]
1. Sorry, by Path Properties I meant properties decorated with `[Path]` -i.e. it needs to support placeholders (and the sanity-checking that's done when the implementation is generated, to make sure that we don't have any placeholders without corresponding path properties).
2. The difference with absolute method paths is that a `BasePath` will *always* override the HttpClient's path, whereas a method path will only override it for that one method.
  - I'm wondering whether we want an exception if someone tries to use a `BasePath` with a HttpClient which has a path, to tell them that, whatever their reasons for doing what they did, it won't have the effect they want.
  - The other option is to forbid absolute `BasePath`s (although they can sneak around this if they use a path property, and that's probably fine), since it could be argued that it's an abuse of them. It makes sense to separate the API as a definition from the URL at which it happens to be hosted, but putting the absolute path in the `BasePath` violates this. (It's also a decision we can change in the future if necessary).

**Comment by mansellan** [comment]
For my purposes, I'd be happy with either option, although I lean to the latter - I have no need of absolute `BasePath`s, and as you say doing so seems to be a violation on principal.

**Comment by canton7** [comment]
Sounds good! If you're happy to put together a PR, that's probably going to be the fastest way to get this done. Happy to give pointers - ImplementationBuilder in particular is a bit gnarly.

**Comment by mansellan** [comment]
Yep happy to do so. My IL is, uh, rudimentary, I'm sure I'll have questions!

**Comment by canton7** [comment]
Hi, how are you getting on? Anything I can do to support you?

**Comment by canton7** [comment]
(I'm working on this now - almost done)

**Comment by mansellan** [comment]
Gosh, sorry :blush:. For work I sidestepped it for my domain problem (REST hosted in Service Fabric). I'd been meaning to decouple it from the specifics and open a PR (even bought a book on IL), but... life got in the way.

As penance, I'll see if work will let me open source RestEase.ServiceFabric as an extension library.
