### ISSUE TITLE
Using Flurl with RestEase....

### ISSUE THREAD

**Issue by natiki** [canton7/RestEase#120]
Hi,

I have been using https://flurl.dev/ which is an intelligent wrapper around HttpClient that deals with:

- Lifetime Issues (https://flurl.dev/docs/client-lifetime/, https://github.com/canton7/RestEase#httpclient-and-restease-interface-lifetimes)
- Adds testability (https://flurl.dev/docs/testable-http/) 

What I am interested in is:

Whether I can make RestEase use Flurl and/or RestEase would be interested in using Flurl under the hood and offering that as an option? While at the same time keeping the above two benefits in place.

**Comment by canton7** [comment]
RestEase and Flurl are basically trying to do the same thing, but in slightly different ways. I don't think it makes sense to combine them in any meaningful way - in order to do so, you'll have to throw away most of the benefits that either one provides.

HttpClient lifetime is more important for Flurl, as it's less easy for the user to control it themselves. With RestEase, by default the lifetime of the HttpClient is closely tied to the lifetime of the instance returned by `RestClient.For`. It's therefore easy to cache the HttpClient instance, by caching the instance returned by `RestClient.For`.

I've been thinking about ways the cache a single HttpClient instance across multiple calls to `RestClient.For`. This is not without its own problems though: rumour has it (though I haven't verified this) that a single HttpClient instance won't react to DNS changes; and HttpClient instances hold state, such as their CookieContainer. Asp.net's HttpClientFactory attempts to address these issues, but it's really quite complicated and not available outside of asp.net. 

For now, then, the advice is to treat the instance returned by `RestClient.For` as if it was a HttpClient instance, and manage its lifetime accordingly.

In terms of testing, the difference here is that RestEase gets the user to write an interface, whereas Flurl methods on a Url instance that the user creates. This means that mocking RestEase is as simple as mocking that interface using your favourite mocking framework. I don't think there's any benefit to trying to write our own mocking framework here - it will never be as good as the mocking frameworks which are already available. It also means that the user can use their favourite mocking framework which they're already familiar with, and they can mock it in a way that's consistent with the rest of their test suite.

**Comment by natiki** [comment]
@canton7 Much appreciate your insights and your time commenting on this for me. And I should have said I **really like** RestEase and what I am able to accomplish with very little code. Thanks for making it available.
