### ISSUE TITLE
Feature Proposal: Parameterized headers

### ISSUE THREAD

**Issue by mbcrawfo** [canton7/RestEase#123]
I'm working with an API that uses request headers to specify filtering, and it allows multiple headers which are combined with an "and" on the backed.  I'd like to be able to do something similar the code below so that I can specify one filter on the request that's always required, but leave the option to add additional filters.  

    [Get("payments")]
    [Header("Search", "merchantId={merchantId}", Parameterized = true)]
    public Task<List<Payment>> GetPayments(
        [HeaderParam] string merchantId,
        [Header("Search")] string search = null,
        int page = 1,
        int pageSize = 100
    )

If you're cool with adding the feature I can probably do a PR in the next couple of weeks.

**Comment by canton7** [comment]
There seems to be a number of things mixed together here...

Your question text talks about combining headers, so there's one on the header that's always required and also optional values. This is already possible:

```csharp
[Get("payments")]
public Task<List<Payment>> GetPayments(
    [Header("Search")] string merchantId,
    [Header("Search")] string search = null,
    int page = 1,
    int pageSize = 100
)
```

(of course, `merchantId` will need to have the value "merchantId={merchantId}`).

The second part is something which appears in your code sample, but not in your question text, and that's the ability to have placeholders in the header value (`{merchandId}`). RestEase doesn't have anything like that anywhere at the moment, so it would be good if anything new applied to everything (path, query, etc etc). Some of the attributes also have a `format` parameter, so anything new would need to work with those.

I kinda wish that `format` was passed to `string.Format` and not `IFormatProvider.ToString` (which would solve this issue), but it's a bit late for that now.

Let me have a think about how best to move forward.

**Comment by mbcrawfo** [comment]
> of course, merchantId will need to have the value `"merchantId={merchantId}"`

Yes, that's what I'd like to avoid.  Needless to say the example is simplified.  Our business rules require that this particular method always has a certain search filter, but I would like to define that filter string in one place instead of repeating it everywhere the method is called.  However that requires RestEase' "Constant Method Headers" gain the ability to support formatting.

**Comment by canton7** [comment]
For the short term, remember you can define an extension method.

**Comment by canton7** [comment]
(also, I'd prefer to tackle this by extending the parameter headers, not the method headers. Something like `[Header("Search", format = "merchantId={0}")] string merchantId` I think.

**Comment by mymys91** [comment]
Is there any way I pass a dictionary headers instead of one-by-one Header parameter?
My flow is client sends a request --> gateway (here, I build another request) --> microservice 
I am using RestEase between gateway and microservice and I need all headers from client since in my microservice will save client info such as IPaddress, Host
Thanks

**Comment by canton7** [comment]
@mymys91 Currently not without [using `IRequester` directly](https://github.com/canton7/RestEase#using-irequester-directly). Feel free to open another issue.

**Comment by canton7** [comment]
One way to solve this would be to re-appropriate `Format`: if it looks like it's got a format placeholder in it (e.g. `{0}`, or `{0:xx}` or something), then we pass it to `string.Format`. Otherwise it continues to work as-is.

I don't think any of the built-in custom format strings use `{` so this should be backwards-compatible, although I guess there's nothing to stop someone from defining their own object as `IFormattable` and accepting these characters, so there's a risk of this being a breaking change for someone (albeit a small one).

**Comment by canton7** [comment]
Implemented what I discussed. In the next version, you'll be able to write:

```csharp
[Get("payments")]
public Task<List<Payment>> GetPayments(
    [Header("Search", Format="merchantId={0}")] string merchantId,
    [Header("Search")] string search = null,
    int page = 1,
    int pageSize = 100
)
```
