### ISSUE TITLE
Combine Request Modifier and Custom HttpClient?

### ISSUE THREAD

**Issue by netclectic** [canton7/RestEase#130]
Is it possible to combine a Request Modifier with a Custom HttpClient?

I'm currently using a custom http client to add a proxy and ignore ssl validation errors, but I also need to be able to handle oauth. 

I was able to get the oauth part to work with a request modifier, as per the readme example, but there is no override that accepts a custom http client as well as a request modifier. 

I'm guessing there is probably a way to implement the oauth part using the custom http client but I couldn't see an obvious way to achieve that.

Is there a way achieve both?

**Comment by canton7** [comment]
The `RequestModifier` is just used with a custom `HttpClientHandler`: [`ModifyingHttpClientHandler`](https://github.com/canton7/RestEase/blob/63e5e0f3c521d88e6cebcf784a95c4eb97d742d9/src/RestEase/Implementation/ModifyingClientHttpHandler.cs, [see here](https://github.com/canton7/RestEase/blob/3e2cd314ad109bd6f3465f88fedebdb4d5023c0d/src/RestEase/RestClient.cs#L127).

You can create your own `HttpClientHandler` instead of using `RequestModifier`, or you can instantiate a `ModifyingHttpClientHandler` directly.

**Comment by netclectic** [comment]
Ok, I see what its doing now.

I already used a custom HttpClientHandler to add retry policies for another api, so I should be able to do everything I need.

Thanks!
