### ISSUE TITLE
Default serialization of query arguments

### ISSUE THREAD

**Issue by Bert-Proesmans** [canton7/RestEase#140]
In my experiments i see that query arguments are serialized according to the machines locale. I suppose they never pass through the JSON serializer.

Is this desired behaviour for types like DateTime? In my opinion these should always be formatted as ISO string.
If it intended, are we required to always provide a Format property to the Query/Path attribute?
Is there another, better fitting, approach?

Thank you in advance!

**Comment by canton7** [comment]
There is a way to force the invariant culture, but turns out it's not in the README.

Set [RestClient.FormatProvider](https://github.com/canton7/RestEase/blob/master/src/RestEase/RestClient.cs#L89), e.g.:

```csharp
var api = new RestClient("http://example.com")
{
    FormatProvider = CultureInfo.InvariantCulture,
}.For<ISomeApi>();
```

All types are, by default, serialized by calling `ToString()` on them. `DateTime` is not special in this regard (and it can't be made special without breaking backwards compatibility). So either you'll need to set the format on each, or you'll need to provide a custom serializer.

**Comment by Bert-Proesmans** [comment]
Great, thank you for the advice.
