### ISSUE TITLE
Ability to add dynamic path variable to every request

### ISSUE THREAD

**Issue by ravensorb** [canton7/RestEase#16]
I am looking for a way to add the same dynamic path variable to every call within a given interface

Here is an example of what I am currently doing
```
[Header("Accept", "application/json")]
public interface ICategoryApi
{
	#region Category
	[Get("/API/Account/{accountId}/Category")]
	Task<Category> GetCategoryAsync([Path] string accountId, [Query("name")]string name);

	[Post("/API/Account/{accountId}/Category")]
	Task<Category> CreateCategoryAsync([Path] string accountId, [Body] Category item);

	[Put("/API/Account/{accountId}/Category")]
	Task<Category> UpdateCategoryAsync([Path] string accountId, [Body] Category item);

	[Delete("/API/Account/{accountId}/Category")]
	Task<Category> DeleteCategoryAsync([Path] string accountId, [Body] string itemId);
	#endregion Category
}
```

Ideally, I'd love it if I could define a more "global" way (either per interface, or per method) to define something like a call back to set the value for the path argument

```
[Header("Accept", "application/json")]
public interface ICategoryApi
{
	#region Category
	[Get("/API/Account/{accountId}/Category")]
	Task<Category> GetCategoryAsync([Query("name")]string name);

	[Post("/API/Account/{accountId}/Category")]
	Task<Category> CreateCategoryAsync([Body] Category item);

	[Put("/API/Account/{accountId}/Category")]
	Task<Category> UpdateCategoryAsync([Body] Category item);

	[Delete("/API/Account/{accountId}/Category")]
	Task<Category> DeleteCategoryAsync([Body] string itemId);
	#endregion Category
}
```
and then allow something like
```
_apiInterface = restClient.For<TInterface>().WithPathParameter("accountId", _accountId);
```
or maybe
```
_apiInterface = restClient.For<TInterface>().WithPathParameter("accountId", (s) => _accountId);
```

**Comment by canton7** [comment]
I think this is a sufficiently niche use-case that it's not worth adding explicit support for it.

An easy way to accomplish this would be to use a custom [`RequestModifier`](https://github.com/canton7/RestEase/#requestmodifier), which manipulates the [`HttpRequestMessage.RequestUri`](https://msdn.microsoft.com/en-us/library/system.net.http.httprequestmessage.requesturi(v=vs.118).aspx). You'd have to use some other placeholder for the account id - `{accountId}` will be picked up by RestEase.

Another option would be to change your base URL - use `[Get("Category")]` and `[Put("Category")]`, then create your rest client like `RestClient.For<ISomeInterface>($"http://example.com/API/Account/{accountId}");`.

**Comment by ravensorb** [comment]
Fair enough -- although I use a LOT 3rd party APIs that follow this behavior.  

That said, breaking it up into 2 restClients with different HttpClients works pretty well for now,

**Comment by canton7** [comment]
I could be open to allowing `[Query]` and `[Path]` attributes on interface properties

**Comment by ravensorb** [comment]
That could be very useful, just not sure of that would help in this case, would it?  Unless there is a way to do a Path on the actual interface with a placeholder however where do you get the value for it at that level without registering some sort of call back?

Or am I missing something :)

**Comment by canton7** [comment]
[See this](https://github.com/canton7/RestEase#variable-interface-headers), but apply it to query/path params rather than headers.

**Comment by ravensorb** [comment]
Ahh, that makes a lot of sense. That would work pretty well.

**Comment by ravensorb** [comment]
Question -- does the framework work with inheritance on interfaces and extract headers from the response?

For example:
```
public interface IApiBase
{
   [Header("X-AccountID")]
   string AccountID {get; set;}
}

public interface ICatalogApi : IApiBase
{
    [Get("/Catalog")]
    Task<Item> GetItemAsync();
}
```
Would that allow the property AccountID to retrieve the header "X-AccountID" from the response stream?

**Comment by canton7** [comment]
For interface inheritance, read the docs. It doesn't explicitly extract headers from the response, but they're available to you if you use one of the method return types which allows access to the raw response.

**Comment by ravensorb** [comment]
Sorry about that -- I see the docs.  Any thought to adding header extraction in the response type?  That would be a pretty cool/useful feature.

**Comment by canton7** [comment]
What do you mean?

**Comment by ravensorb** [comment]
I run into a number of APIs that do rate limiting and they send back the current limit in headers in the response.  It would be cool if I could add a property on my interface, mark it with a header, and it would get populated as part of the "deserialization" of the result.

For example
```
public interface ICatalogApi : IApiBase
{
   [Header("X-Limit")]
   int CurrentLimit{get; set;}

    [Get("/Catalog")]
    Task<Item> c();
}

var result = await _apiItem.ICatalogApi(); // this would pull the header out and apply it to the property on the API object
if (_apiItem.CurrentLimit > API_MAXLIMIT)
{
    // do something
}
```

**Comment by canton7** [comment]
I'm not going to extract response headers to properties on the interface - that would break the pure model, and would break thread safety. It would also make the interface really awkward to use. 

I can't extract them to things on your custom response type, because I'm not in the business of writing custom deserializers which somehow work alongside json.net. 

I return them in `Response<T>` responses, which is the only reasonable thing I can do. I also make them available to custom response deserializers, so that you can write a response deserializers which puts the headers you're interested in into your response object, if you want.

**Comment by ravensorb** [comment]
It wouldn't be on the dto it would be on the object your library is creating (returned from call to For<>).

It's ok, you are correct I can use the response type, it would just be simpler as a user to not have to extract the response headers after every call 🙂

**Comment by canton7** [comment]
Ok, so they would be on the interface?

> I'm not going to extract response headers to properties on the interface - that would break the pure model, and would break thread safety. It would also make the interface really awkward to use.

**Comment by ravensorb** [comment]
Yes I was thinking it would be on the interface.  Your point is good on thread safety although not sure that is a big issue.  As for awkward, how so?

**Comment by canton7** [comment]
The thread safety is a huge issue. The current model is completely safe. Yours is racey. I'm not going to support and promote a model that is racey.

Its awkward because you now send a request, get a response which contains most of what you're interested in, and also have to look at this otherwise-unchanging object to get some other info about the response which for some inexplicable reason isn't contained with the rest of the response. You also have to hope that you read them before someone else makes a request and overwrites them... 

I'm afraid the weekend is now over, and I'm not going to have time to write long and detailed responses to you explaining why your ideas  (largely) go against the philosophy of RestEase, and decent architecture and API design in general. 

I'll consider the interface-level path and query params earlier in this issue, but I'm afraid that otherwise I'm done here.

**Comment by canton7** [comment]
Path properties added.

**Comment by canton7** [comment]
Released, therefore closing this.
