### ISSUE TITLE
Binary incompatibilities in 1.5.1

### ISSUE THREAD

**Issue by r-bennett** [canton7/RestEase#173]
First off should say that we really like the library, it's super useful and we're using it fairly widely (50+ projects) in our codebase at G-Research.

The latest release has a couple of binary incompatibilities in it though which are causing us some headaches, in particular this one: 
https://github.com/canton7/RestEase/commit/8121fd1c857d6905bf5a81c674f3315e90185b92#diff-670b79a8f3b83d14f6d9c81e7fcfcf351d19f007cd4576cb5a08a63079a83eaeR105

We're extending the `Requester` class to create an instance with baked in Polly retries using some common retry policies that make sense for our networks. I see the new comment on that class suggests we're no longer safe to be doing this, which is a bit disappointing for a part of the public API. Is there a safe way we can continue to do what we're doing?

Thanks,
Richard

(Edited to reference the right method)

**Comment by canton7** [comment]
The original intention was to keep binary compatibility on `Request` and allow it to be extended by users, but in practice it turned out to be very hard to do this while still adding functionality. The doc comment was updated to reflect reality, rather than being a policy change at that point.

Would you mind sharing how you're subclassing `Requester`? I'm happy to explore other possible approaches, which may be more user-friendly for others wishing to do the same thing. I'd also like to see how you're incorporating Polly: that came up in #89, where the suggestion was that people were implementing it at the `HttpClientHandler` level.

**Comment by r-bennett** [comment]
Sorry for taking a while to respond, I've been off work for a bit.

Unfortunately because of corporate network restrictions it's a bit tricky to share the code directly, although I probably could get it outside if it's going to be useful.

The purpose of the lib is partly to integrate Polly, and partly to allow us to set some different `HttpClient` defaults around auth and connection sharing. The setup is:

- A static class `RetryingRestClient` with various `For<T>()` methods which let you specify just a base address and then pick up our default Polly `Policy` and `HttpClient`, or also inject your own custom `Policy` and/or `HttpClient`. So you use it like `RetryingRestClient.For<IGitHubApi>("https://api.github.com");` or `RetryingRestClient.For<IGitHubApi>(myClient, myPolicy);`
- These methods all construct an `IRequester` instance, and return `RestClient.For<T>(thatInstance)`
- The `IRequester` instance they construct is an instance of our subclass of `Requester` which takes the `Policy` and `HttpClient` and overrides `Requester.SendRequestAsync(IRequestInfo info, bool readBody)`.
- The whole body of that method is inside a policy retry, i.e. it's `Requester.SendRequestAsync(IRequestInfo info, bool readBody) { return _policy.ExecuteAsync(async () => { // body here };}`
- That body is basically a direct copy of most of what's in the base class, up to the error handling https://github.com/canton7/RestEase/blob/master/src/RestEase/Implementation/Requester.cs#L444-L472. We then have some custom logic for our error handling to work out whether the error ought to be retryable (e.g. it's not forbidden or bad request or similar), and if it's a retryable error then we throw a custom `RetryableException` type which is handled by the `Policy`

So overall we'd like a way to inject our own `HttpClient` (or rather our own `HttpMessageHandler` into the client), a way to run requests which expose the raw errors for us to handle instead of throwing `ApiExceptions`, and a way to wrap those requests with a Polly `Policy`

**Comment by canton7** [comment]
OK, I follow thanks.

I'm curious as to why you need to subclass `Requester` to do that, rather than supplying it with an `HttpClient` which is configured to use your own `HttpMessageHandler` (or use [`PolicyHttpMessageHandler`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.http.policyhttpmessagehandler?view=dotnet-plat-ext-3.1)).

`HttpMessageHandler.SendAsync` is a good place do things like sending multiple requests, or inspecting the raw response.

However, since you've considered this and you're not doing it, there must be some additional contraints you have, and I'd like to understand what those are.

**Comment by r-bennett** [comment]
I wasn't aware of `PolicyHttpMessageHandler` tbh (this lib probably pre-dates it) but it sounds promising. Either way, doing it through the injected handler sounds like a better approach that should free us from the dependency on the `Requester` interface.

I'll have a go at updating the library to that approach - if I discover the reason why it wasn't done that way in the first place and I'm still stuck on it then I can reopen, but otherwise I think we're good to resolve this one.

Thanks for the help

**Comment by canton7** [comment]
Thanks! I'm open to introducing a layer between Requester and HttpClient if you need. I'll also update the docs here to offer some more guidance.

**Comment by canton7** [comment]
The next version of RestEase will have `RestClient` and `RestClient.For<T>` overloads which take a `HttpMessageHandler`, making it easier to use `PolicyHttpMessageHandler`, and the README will also contain instructions on how to do this.

**Comment by canton7** [comment]
Closing as I think we're done here. Feel free to reopen if you disagree.
