### ISSUE TITLE
Add request info to ApiException

### ISSUE THREAD

**Issue by lencharest** [canton7/RestEase#30]
It would be helpful if `ApiException` carried some information about the failed request. For example, the request method and request URI.

**Comment by canton7** [comment]
That's a fair request

**Comment by arkoc** [comment]
Can I grab it?

**Comment by canton7** [comment]
Go for it!

I'm stuck in a bit of a quandary, where I've removed VS2015 from my home computer, but .NET Standard projects under VS2017 can't yet target .NET 4.0.

**Comment by canton7** [comment]
I hadn't heard anything in a week, and I wanted to include this in the next release, so I'm afraid I grabbed this.

**Comment by phillijw** [comment]
Can you get any of this info before calling the api method? Does this solve the problem of signing a request? For instance, header of X-API-SIGNATURE would be a hash of the timestamp, uri endpoint, request method, body, and api-secret. If we don't have access to the endpoint, how would we set this ahead of time?

**Comment by StefH** [comment]
Another thing which floats into my mind; is it also possible that restease can log the request before it's send to the endpoint?

**Comment by canton7** [comment]
@phillijw I'm afraid I don't understand the question. This exception is thrown because a request went wrong - it will never be thrown before the request happens. I'm not sure why you wouldn't have access to the endpoint, after making a request to it.

Guys, this is a 2-year-old issue, which was successfully closed. It's done and dusted. Please don't bring it back to life!
