### ISSUE TITLE
Possible support for multipart/form-data?

### ISSUE THREAD

**Issue by ravensorb** [canton7/RestEase#38]
I am curious if it is possible to use RestEase for APIs that leverage multipart/form-data in a more structured way?

Here is an example of what I'd like to "post":
```
POST /API/Image
Accept: application/xml
Content-Type: multipart/form-data; boundary=25112bca3fa7474e9874f9e8654c27aa
--25112bca3fa7474e9874f9e8654c27aa
Content-Disposition: form-data; name="data"
<Image>
<filename>2014 red racer.jpg</filename>
<description>Our new 2014 Racer model in Red!</description>
<itemID>5</itemID>
</Image>
--25112bca3fa7474e9874f9e8654c27aa
Content-Disposition: form-data; name="image"; filename="2014 red racer.jpg"
Content-Type: image/jpeg
.... Image data ....
--25112bca3fa7474e9874f9e8654c27aa--
```

I think I can do this with using MultipartFormDataContent as a parameter type.  The only issue is with that I loose control over the clean API that RestEase creates.

Ideally I'd like do something like this (this is just a thought)

```
public interface IMyApi
{
   [Post("/API/Item"]
   [BodyType(BodySerializtionMethod.MultiPart)]
   Task<Response<ApiResponse>> CreateImage([BodyPart(Name="data")] ImageMetaData metaData, [BodyPart(Name="image"] Stream imageData);
}
```

**Comment by canton7** [comment]
Yeah, it might be possible to build an abstraction around multipart form data. The issue is whether such an abstraction is cleaner than the original HttpClient classes... Do note that you've lost the "2014 red racer.jpg" name and the "image/jpeg" content-type in your "something like this" example - in reality it looks like you might be needing a `FileBodyPart` attribute....

Also, it is possible to write extension methods on your RestEase interface which take care of the heavy lifting of constructing the `MultipartFormDataContent` stuff while still presenting a nice interface. 

Also, make sure you read this: https://github.com/canton7/RestEase#i-want-to-upload-a-file

**Comment by canton7** [comment]
Building an abstraction over `MultipartFormDataContent.Add` might not be too bad - that's limited to a `HttpContent` content (which could also be a string, stream, etc), an optional string name, and an optional string filename. However this would force you to hard-code the name and the filename, so I'm not sure how useful this would be in practice. It also wouldn't solve the issue of your "image/jpeg" Content-Type header, so you'd still need to pass a StreamContent with this header set there.

Maybe the solution here is to make it easier for people to add their own methods onto RestEase interfaces. This could either mean exposing the `IRequester` used by the interface so that people could interact with it from extension methods on the interface, or allowing RestEase interfaces to be abstract base classes and allowing people to define their own methods. That probably comes with its own set of challenges though...

**Comment by ravensorb** [comment]
Hmm good point on the filename issue -- for that specific type of scenario, I wonder if there would be a way to be dynamically set the filename (static would make it less than ideal).

Also, really like the idea of supporting extension methods for IRequester -- that would make it easier to implement retry logic and paging (requesting multiple pages of data at once).

**Comment by canton7** [comment]
> That would make it easier to implement retry logic

I don't think what I'm proposing would help with retry logic - for that you'll want to subclass Requester or provide a RequestModifier.

**Comment by ravensorb** [comment]
i just started looking into the idea of using a request modifier for this exact use case :)
