### ISSUE TITLE
.NET 4.0 ?

### ISSUE THREAD

**Issue by StefH** [canton7/RestEase#39]
Documentation says : ` .NET Framework 4.0`, however I cannot use it in a .net 4.0 project ?

**Comment by canton7** [comment]
Ah damnit. I had to remove support in 1.4.0, since the Microsoft.Bcl.Async package didn't play nicely with csproj-based .NET Core projects. You can use version v.1.3.3 or earlier, or if you've got some time to spare, figure out how to add support again. Reference: https://github.com/dotnet/cli/issues/5993

**Comment by StefH** [comment]
If you have indeed troubles with `Microsoft.Bcl.Async`, I guess there is no easy solution.

A workaround could be that you create a normal (old) `.net 4.0` project which references all the same `.cs` files. And copy the output somehow to the final folder / NuGet package.

**Comment by canton7** [comment]
Yeah, it would be possible to have separate projects. It's a bit of a pain since nuget became much more tightly integrated with .NET Core, and it wants to build the package from the stuff it finds in the csproj.

On the other hand, .NET 4.0 is no longer getting security updates, technical support, or hotfixes. It's dead. 

I'm going to remove it from the readme, yes.
