### ISSUE TITLE
Move Attributes to RestEase.Annotations

### ISSUE THREAD

**Issue by MiloszKrajewski** [canton7/RestEase#47]
I guess it would be nice if all attributes were moved to separate package, let's say `RestEase.Annotations` so interface won't have dependency on specific version of `RestEase` (`RestEase.Annotations` should not change that often).

**Comment by canton7** [comment]
What's the motivation?

**Comment by MiloszKrajewski** [comment]
Hi,

Let's imagine two teams releasing interfaces to their services as RestEase interfaces. Let's say Netflix and Amazon Prime. You are writing media player which stream from both. There is one problem, though, Netflix uses RestEase 1.4 while Amazon released them with dependency on RestEase 2.0. Version 2.0 contains braking changes so application does not compile or just does not work a s expected. The breaking changes are not on interfaces though (they are describing REST/HTTP, after all, and it does not change that fast) but somewhere "in the engine" (for example, different way RegestModifier needs to be implemented).

The solution is to release interfaces depending on thin abstraction: RestEase.Attributes (or RestEase.Annotations). It can be used with any version of RestEase (the "engine"), so the consumer (of the interface) makes the call.

Recently, with .NET core, you see a lot of this: `Microsoft.Extensions.Logging.Abstractions` vs `Microsoft.Extensions.Logging`, `Microsoft.Extensions.DependencyInjection.Abstractions` vs `Microsoft.Extensions.DependencyInjection`, `System.Runtime.Serialization.Primitives` vs `System.Runtime.Serialization`.

Well, it is just about "decoupling abstraction from implementation".

I can imagine something like this: "We cannot use your interface assemblies as you use RestEase 2.0, and we are still deep in RestEase 1.4, and we are not planning to upgrade for a while". "Don't worry, it's still based on RestEase.Annotations 1.0. You you can use them with RestEase 1.4 without any problem."

**Comment by canton7** [comment]
Is this actually a scenario you face? 

If not, let's hold off until Amazon start releasing their apis as RestEase interfaces... I don't think that's a good usage of RestEase anyway: I think if the interfaces as implementation details of the comms layer, rather than as things which are exposed, in any semi-complex application anyway.

**Comment by canton7** [comment]
To be honest, it would make much more sense to release swagger definitions of the interfaces and not use RestEase at all in those sorts of situations.

**Comment by canton7** [comment]
Also to add, when people do release their apis as packages, they are always (in my experience) full wrappers around their api, rather than "here's some stuff, but you'll need to install this other package and do X, Y and Z to make this work". For example the AWS package is a fairly intelligent wrapper around the rest api. 

Also I think it's fairly doubtful that a RestEase 1.4 interface would work with RestEase 2.0. Whether RestEase can generate an implement for an interface depends on a lot more than just what attributes have been used.

**Comment by canton7** [comment]
Closing as no response.
