### ISSUE TITLE
Customise serialisation through custom attributes

### ISSUE THREAD

**Issue by barclayadam** [canton7/RestEase#51]
An integration with an API that has a wrapper JSON property around all response/requests. This is noisy and I'd like to NOT have to create a custom class for each of these wrappers (i.e. `ContactResponse`, `ContactsResponse`, `InvoiceResponse`, `InvoicesResponse`, `InvoiceCreateRequest`) as it gets noisy and tedious very quickly.

A previous implementation of this integration used RestSharp that had a simple property `RootElement` you could set per request to skip the root element and deserialise the inner.

I thought I could create a custom serialiser / deserialiser. My issue is when it comes to that method I only have the body of the request/response. I'd like to know what `method` was used, so I could look at attributes:

````c#
public T Deserialize<T>(string content, HttpResponseMessage response, IRequestInfo requestInfo)
{
   var rootElement = requestInfo.Method.GetCustomAttributes<JsonRoot>();
   return DeserialiseFromRoot<T>(rootElement, content);
}
````

It requires the Method to be added to RequestInfo (non-breaking) and access to the `RequestInfo` in deserialisers etc. which is breaking.

Any thoughts on what could be achieved, given current API and/or changes?

**Comment by canton7** [comment]
Fair request.

I can think of two ways to do this:

1. The static ctor for the generated implementation grabs the MethodInfo for all methods being implemented. When a generated method is called, the appropriate MethodInfo is added to the RequestInfo. This has a penalty the first time that a generated implementation is instantiated.
2. When generating the implementation for a method, look at the CustomAttributeDatas for the being method implemented, and emit IL which describes how to instantiate all attributes, adding all to a collection on the RequestInfo.

The first has a cost when the generated type is first instantiated. There's an additional reflection cost when the user accesses any attributes from the MethodInfo.

The second puts the cost of reflection when the type is first defined, and has an additional small runtime cost to instantiate all of the attributes on each method call (whether they're accessed or not), but there's no additional reflection cost to accessing the attributes on a method.

The second is probably easy to write, since the complexity is localised to each method, whereas the first spreads the complexity over the fields, static ctor, and methods. I wouldn't worry about either, though.

**Comment by barclayadam** [comment]
Thanks for the reply.

A few more thoughts:

* Not everyone is going to be using this, so keeping the overhead small is important. I think creating each attribute on every call, performance wise, may not be the best option here. Which may eliminate option 2 unless we can provide a function that lazily-constructs? i.e. `requestInfo.GetMethodAttributes()`

* Is there value in providing the `MethodInfo` anyway, not just the attributes? Perhaps looking at containing type, or method name, generic parameters even would be useful to some? It may be worthwhile exposing this now instead of another change in the future?

* With option 1 there is an additional cost paid for grabbing custom attributes, but at least that is up to the user. They could cache, or just accept the overhead, depending on their needs (for the record, I would just accept the overhead).

**Comment by canton7** [comment]
> I think creating each attribute on every call, performance wise, may not be the best option here

Yeah, but if they're not using custom attributes, there's no cost, because there are no custom attributes to instantiate 😄 . If they *are* using custom attributes, then it has to be instantiated, either by my code or by the Reflection classes. If they're not using custom attributes at all, then option 2 is the fastest, since we eliminate the reflection when the type is first instantiated.

> Is there value in providing the MethodInfo anyway, not just the attributes? Perhaps looking at containing type, or method name, generic parameters even would be useful to some? It may be worthwhile exposing this now instead of another change in the future?

Yeah, I'm inclined to agree.

I've been planning to deprecate the interfaces for serializers/deserializers and move to abstract base classes for a while, which would let me do things like change the parameters which serializers are given. This would be required to allow FieldInfo for params to be given to custom param serializers.

**Comment by barclayadam** [comment]
I was thinking you would be indiscriminate about what attributes are passed, including all of the ones that actually make RestEase work (`Get`/`Post` etc.) so there would always be a cost to handling attributes if they are instantiated.

**Comment by canton7** [comment]
In option 2, I wouldn't add RestEase's attributes, I think - all of the information in those attributes should already be available.

In option 1, of course, the question doesn't even arise.

To be honest, I could use a static `Lazy<MethodInfo>` and `Lazy<FieldInfo>` - then we defer even that cost until the user first requests it.

**Comment by barclayadam** [comment]
Having `IRequestInfo` in more places I think makes sense in general. A way of accessing details about the 'current' request seems useful in many scenarios of customisation, not just serialisation / deserialisation. 

I've not dived too much in to the code yet, just trying to get a feel for what I can / cannot do. I needed something more flexible than RestSharp, an like what I see so far :)

**Comment by canton7** [comment]
Ah, there is complexity that I hadn't considered, which is supporting interface inheritance. That shouldn't be too hard, though. Just more data to pass around....

**Comment by barclayadam** [comment]
Ah OK, I see. That does make sense.

I may be wrong, but I think handing out the `MethodInfo` for the calling method could allow you to skip much of the complexity in RestEase and push it out to the user. You do not need to worry about inheritance, what scenarios the user comes up with etc. (for example how about attributes on the parameters as well?)

The only thing you would care about is reducing the perf. overhead of creating / grabbing these MethodInfo instances in the first place.

**Comment by canton7** [comment]
> I may be wrong, but I think handing out the MethodInfo for the calling method could allow you to skip much of the complexity in RestEase and push it out to the user

Yeah I agree. 

>  (for example how about attributes on the parameters as well?)

This is what I was talking about earlier with FieldInfos. The IRequestParamSerializer and IRequestBodySerializer would both need to be given a FieldInfo.

**Comment by barclayadam** [comment]
Right yeah. Parameters are `ParameterInfo`, which is what they would need? 

What's your current plan for RestEase, in terms of changes here and others like the deprecation of the interfaces in favour of abstract classes?

**Comment by canton7** [comment]
Yep, brain fart. I need my afternoon tea 😄 

The project's pretty much on the back-burner (life takes over...), but I'm happy to add stuff as people request it. I'm in the middle of refactoring the implementation generation code to make it easier to add alternative generators (I'm looking forward to source generators in the next version on VS, for example). There could also be value in a Fody generator. One of those is probably going to be the Next Big Thing for RestEase.

The deprecation of the interfaces has been in the pipeline for a while, but there hasn't been any reason to start doing it, as there hasn't been a need to break those interfaces. Any change would be backwards compatible.

For this, PRs are of course welcome, otherwise I'll get around to it at some point soonish. We're kicking off a new project at work, so my free time is somewhat limited right now.

**Comment by barclayadam** [comment]
Ok, sounds great. Compile-time generation would be pretty nice from a performance POV, eliminating the overhead of generating the proxy class.

There's quite a bit going on my end at the moment too, I'll see if I can dive in at some point and make some progress here if you do not tackle this first.

I think for some of what I want to do I'm going to need these two changes in. Depends on priorities.

**Comment by canton7** [comment]
Right, that should work!
