### ISSUE TITLE
Visual Studio complains method is not 'async'

### ISSUE THREAD

**Issue by nguillermin** [canton7/RestEase#54]
I have code that looks like this

    var APIResponse = await someApi.GetStudentsAsync(); // "The 'await' operator can only be used within an async method. Consider marking this method with the 'async' modifier and changing its return type to 'Task'"

    public interface ISomeApi
    {
        [Get("students")]
        Task<Response<List<Student>>> GetStudentsAsync();
    }

Visual Studio won't build this, claiming the method is not async? This code was mostly cribbed from the Quick Start documentation.

**Comment by canton7** [comment]
I'm afraid I'm not the right person to teach you how to use async/await. If you're writing a synchronous program, I recommend doing `var apiResponse = someApi.GetStudentsAsync().Result;`

**Comment by roryprimrose** [comment]
This error happens when you don't put the async modifier on the method that uses an await keyword.

Your broken code is probably something like this:
```
public Task DoSomething()
{
    var APIResponse = await someApi.GetStudentsAsync(); 

    // do something with APIResponse
}
```

This needs to be written as

```
public async Task DoSomething()
{
    var APIResponse = await someApi.GetStudentsAsync(); 

    // do something with APIResponse
}
```

You should avoid using ```.Result``` and ```.Wait()``` as this can cause deadlocks.

You should also use ```.ConfigureAwait(false)``` unless you need the continuation (all code after the await) to execute on the original thread. You almost never want the continuation on the original thread. For example, in ASP.Net this would cause the continuation to try to get onto the original HTTP request thread which is probably now serving another client.

For example

```
public async Task DoSomething()
{
    var APIResponse = await someApi.GetStudentsAsync().ConfigureAwait(false); 

    // do something with APIResponse
}
```

If there is no continuation, then you shouldn't use async/await because the compiler will put a state machine into the IL which is an unnecessary overhead. Without a continuation you can just return the task.

For example

```
public Task DoSomething()
{
    return someApi.GetStudentsAsync(); 
}
```
I blogged a few years back about some good async resources. I highly recommended reading the links at http://www.neovolve.com/2013/10/16/recommended-reading-for-developers-v2/.

**Comment by roryprimrose** [comment]
Oh, forgot one. You should pass CancellationToken parameters all the way down as well so you can deep async cancellation support. If you have async loops then you can also exit the loop early if the token indicates it has been cancelled.

**Comment by canton7** [comment]
It would be worth checking whether he's writing a simple console app first... If he is, then .Result is fine, and trying to make an async method is going to be even confusing if you don't know what you're doing.

**Comment by canton7** [comment]
Anyway, I'm afraid this isn't the right forum to each someone async/await.
