### ISSUE TITLE
Save assembly

### ISSUE THREAD

**Issue by netclectic** [canton7/RestEase#69]
Is it possible to save the assembly that is generated? 

It looks like the assembly save methods are not currently available in .net core / standard but it should be possible with the full framework.

What is the performance impact likely to be compared between generating the assembly on the fly over and over and generating the assembly once and saving it for reuse? It seems to me it would make sense to save and reuse.

**Comment by canton7** [comment]
I did have a play around with this a while back. It's possible, but not trivial, mainly due to the error reporting needed. I also need to correctly identify all of the RestEase interfaces: this sounds easy, but I think that Refit ran into significant difficulties here at one point, so there may well be hidden complexities.

The long-term plan is to allow generation of types at compile-time using Fody. This approach has some advantages over saving a separate assembly:

1. I think two assemblies could be confusing. It's possible for the one containing RestEase types could be lost. Fody would let me insert the RestEase types into the user's assembly.
2. It would allow RestEase to implement internal interfaces.

While I agree with you that it feels nicer to generate the types at compile-time, I've never actually heard anyone mention that it takes a long time to generate the types at runtime, so I'm not sure how much of a practical issue it is. It would, however, allow supporting platforms which don't support TypeBuilder, which would be a big plus.

**Comment by netclectic** [comment]
The Fody approach sounds feasible, I haven't played with it yet but it's been on my radar for a while. 

Thinking about it some more, performance is not likely to be a real issue, in my use-case anyway, as the api will likely be generated once at system startup or lazily the first time it is requested, but the same instance will be reused thereafter.

**Comment by canton7** [comment]
RestEase caches the generated types anyway. The type is generated when it's first requested. Thereafter, calling `RestClient.For<T>` instantiates a new instance of the type.

**Comment by canton7** [comment]
Closing as the discussion seems to be complete
