### ISSUE TITLE
Trouble Adding 1.4.4 to a .NET 4.6.1 class library project

### ISSUE THREAD

**Issue by ravensorb** [canton7/RestEase#72]
I am trying to add RestEase 1.4.4 to a .NET 4.6.1 framework class library and I am getting the following error

> The package 'RestEase' tried to add a framework reference to 'System.Web' which was not found in the GAC. This is possibly a bug in the package. Please contact the package owners for assistance.

Note: I tried adding System.Net.Http before adding RestEase and I still get the error.  Any ideas?

**Comment by canton7** [comment]
Interesting... Did it get you to install the Newtonsoft.Json NuGet package?

**Comment by canton7** [comment]
I can't reproduce. VS 15.3.5, new framework class library, add RestEase to NuGet packages.

**Comment by ravensorb** [comment]
I'll look at reproducing it. I found that if I added Newtonsoft and System.Net.Http manually, I can add RestEase.  The odd part is, I get the error mentioned above and yet the reference is still added.

**Comment by canton7** [comment]
If you try to install RestEase, does it prompt you to install Newtonsoft.Json?

**Comment by canton7** [comment]
Hi, any response?

**Comment by nzhulikov** [comment]
@canton7 Hi, I had this error too. I tried to install System.Net.Http manually, but it seems like a problem with the package and its dependencies because there are little yellow warning triangles on each reference. After this, RestEase was installed without any errors, but I conquer another problem. This mock code fails:

```
apiMock.Setup(api => api.AuthenticateAsync(wrongCredentials))
    .ThrowsAsync(new ApiException(
        HttpMethod.Post, 
        default(Uri), 
        (HttpStatusCode)422, 
        "Wrong credentials", 
        default(HttpResponseHeaders), 
        default(HttpContentHeaders), string.Empty));
```

With `MissingMethodException`: "Void RestEase.ApiException..ctor(System.Net.Http.HttpMethod, System.Uri, System.Net.HttpStatusCode, System.String, System.Net.Http.Headers.HttpResponseHeaders, System.Net.Http.Headers.HttpContentHeaders, System.String)"

I tried to alter ctor, but the same exception is being thrown. I thought it happens because of some of the dll's missing, but I discovered that my test's /bin/Debug directory has RestEase.dll, System.Net.Http.dll and its dependencies present.

**Comment by nzhulikov** [comment]
@canton7 Maybe this problem relates to:
> https://github.com/Microsoft/BotBuilder/issues/3615
Because I have a reference to a netstandard 2.0 project in my tests project.

**Comment by nzhulikov** [comment]
@canton7 @ravensorb Guys, I confirm that this is a problem with System.Net.Http and referencing netstandard 2.0 projects. I removed any references, RestEase was installed correctly via NuGet, no errors and everything works as expected.

**Comment by nzhulikov** [comment]
@canton7 I tried to put this code as a workaround (as mentioned [here](https://github.com/dotnet/sdk/issues/1499)):
```
  <Target Name="UpdateOriginalItemSpecs" AfterTargets="ResolveAssemblyReferences">
    <ItemGroup>
      <ReferencePath>
        <OriginalItemSpec>%(ReferencePath.FileName)</OriginalItemSpec>
      </ReferencePath>
    </ItemGroup>
  </Target>
```
But it doesn't help. I still have `MiessingMethodException`.

**Comment by nzhulikov** [comment]
I just switched to NET Core and everything works now.

**Comment by canton7** [comment]
> but it seems like a problem with the package and its dependencies because there are little yellow warning triangles on each reference

Seeing the output of `dotnet restore` / `dotnet build` would have been helpful, as that often says *why* there are warnings.

> With MissingMethodException: "Void RestEase.ApiException..ctor(System.Net.Http.HttpMethod, System.Uri, System.Net.HttpStatusCode, System.String, System.Net.Http.Headers.HttpResponseHeaders, System.Net.Http.Headers.HttpContentHeaders, System.String)"

That error is caused by you linking against one version of RestEase, but running against another version. Perhaps Nuget installed one version for your .NET Framework project, but resolved a different version for your .NET Core project?

**Comment by nzhulikov** [comment]
@canton7 
> Seeing the output of dotnet restore / dotnet build would have been helpful, as that often says why there are warnings.

Sorry, already wiped out old projects. Everything works now with the .NET Core. 

> That error is caused by you linking against one version of RestEase, but running against another version (I changed the signature of that ctor in 1.4.0).

I used same 1.4.4 version of RestEase in both projects. Follow [this link](https://github.com/dotnet/sdk/issues/1499), I think my issue came out of an issue described there.

**Comment by canton7** [comment]
I don't see anything in there to do with MissingMethodException?

**Comment by nzhulikov** [comment]
@canton7 Oops, [here](https://github.com/Microsoft/BotBuilder/issues/3615) it is. Someone had this error with BotBuilder. My issue has the same nature. Removing references to .netstandard 2.0 projects makes everything ok. But I run my shared code for Xamarin app on .netstandard and chosen frameworks depend on .netstandard, so it is not my way. Instead, I switched test projects to .NET Core.

**Comment by canton7** [comment]
Sorry - this slipped off my radar. Are you still having this issue?

**Comment by nzhulikov** [comment]
As far as I remember - no, switching test projects to core helped. It's been a while, I already changed my job 😄 Thanks for asking, anyway! We use restease currently without any trouble so far.
