### ISSUE TITLE
Dispose responses in Requester?

### ISSUE THREAD

**Issue by javicrespo** [canton7/RestEase#82]
When looking at the Requester class, I see a few methods where HttpMessageResponses are not returned to the upstream caller and are not disposed explicitly. 

Example:

https://github.com/canton7/RestEase/blob/master/src/RestEase/Implementation/Requester.cs#L466

Won't that leak?

**Comment by canton7** [comment]
In theory, yes, good point.

In practice HttpResponseMessage is only IDisposable to dispose the HttpContent it owns, which is only IDisposable to dispose the stream created with ReadAsStreamAsync (if that method was ever called). Since we return the stream from ReadAsStreamAsync to the user (and document that the user should dispose it), we shouldn't dispose the HttpResponseMessage in this case.

So the only case we *could* fix is the one you highlighted, and technically that doesn't matter because it won't do anything anyway. We should fix it though, and document the others.

**Comment by javicrespo** [comment]
Ok.
So, for example, in the following method, there is no need to dispose the response, is there?

https://github.com/canton7/RestEase/blob/master/src/RestEase/Implementation/Requester.cs#L429

After calling _ReadAsStringAsync_ the underlying stream resources will be cleaned automatically (?)

**Comment by canton7** [comment]
In that case there won't be an underlying stream resource (well, there will, but it's a MemoryStream, which is IDisposable but doesn't need disposing). Agreed we *should* dispose it there as well.

**Comment by javicrespo** [comment]
Makes sense :+1:

**Comment by canton7** [comment]
(And we should comment the other cases)
