### ISSUE TITLE
Question: how to make an enum-value lowercase when used as [Path] ?

### ISSUE THREAD

**Issue by StefH** [canton7/RestEase#95]
I've defined this API method:

``` c#
[Get("/{network}/methods")]
Task<string> GetMethodsAsync([Path] NetworkType network);
```

Where **NetworkType** is an enum defined as:
``` c#
[JsonConverter(typeof(StringEnumConverter))]
public enum NetworkType
{
    [JsonProperty(PropertyName = "a")]
    A,

    [JsonProperty(PropertyName = "b")]
    B
}
```

When sending a request, the full url which is created by RestEase is like:
`https://test.com/A/methods`
instead of
`https://test.com/a/methods`

**Comment by canton7** [comment]
There's nothing built-in currently: we just call `ToString` on the enum value. You could use [RequestQueryParamSerializer](https://github.com/canton7/RestEase#serializing-request-parameters-requestqueryparamserializer)

**Comment by StefH** [comment]
Would it be possible that you also interpret the `JsonConverter` and `JsonProperty` annotations in a next release? So that an enum can be annotated?

**Comment by canton7** [comment]
Did you mean to use `[EnumMember(Value = "a")]` rather than `[JsonProperty(PropertyName = "a")]`? Json.net will ignore the latter on enum members.

I could potentially add support for serializing path parameters using json.net (this would mirror the existing functionality for query parameters, but is significantly less useful). Alternatively I could add support for DisplayAttribute.

**Comment by StefH** [comment]
In that case, support for `[EnumMember(Value = "a")]` would be the best solution.

(Adding a `DisplayName` attribute on an enum member is not allowed.)

**Comment by canton7** [comment]
I am not going to read json.net's attributes directly. That's a recipe for disaster.

So we can use DescriptionAttribute, DisplayAttribute, a custom attribute, or you can define a java-style enum like this:

```csharp
public struct NetworkType
{
    private readonly string value;
    private NetworkType(string value) => this.value = value;
    public override string ToString() => this.value;

    public static NetworkType A { get; } = new NetworkType("a");
    public static NetworkType B { get; } = new NetworkType("b");
}
```

**Comment by StefH** [comment]
Your proposal with the java-style enum works fine for me now. However for the future DescriptionAttribute or DisplayAttribute would be nice if that' supported.

**Comment by canton7** [comment]
I'm in two minds about whether to silently start using an attribute, or whether to require the user to pass a format string.

This also applies to more than just path params: query params, query maps, properties, etc, are all effected. Some, e.g. query maps, can't have a format string specified.

If we apply it to everything, that's a *lot* of reflection we're suddenly introducing, as every ToString call now needs a .GetType().IsEnum check.

**Comment by StefH** [comment]
Then passing a format-string or a format function would be the best option.

Example 1
``` c#
Task<string> GetMethodsAsync([Path, Format="..."] NetworkType network);
```

Example 2
``` c#
Task<string> GetMethodsAsync([Path, FormatFunction=x => x.ToString().ToLower() ] NetworkType network);
```

**Comment by canton7** [comment]
That's not valid C#. You can't put lambdas in attributes.

**Comment by Sharparam** [comment]
@canton7 

>> In that case, support for [EnumMember(Value = "a")] would be the best solution.

> I am not going to read json.net's attributes directly. That's a recipe for disaster.

[`EnumMemberAttribute`](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.serialization.enummemberattribute?view=netframework-4.8) is not part of Newtonsoft.Json, it's in the .NET Framework/Core/Standard.

I'm hitting this issue as well now where I have an enum being inserted into the path but the API uses names that are not idiomatic C# (so I use `EnumMember` to supply the API name of the enum values).

Would it be a lot of work to add the ability to specify a serialization method for path parameters akin to `QuerySerializationMethod` for query parameters?

I could work around it currently by using `string` in the interface method and then using an extension method to supply the enum value which just serializes it or uses the `EnumMemberAttribute` directly, but it doesn't feel ideal.

You mentioned `RequestQueryParamSerializer` but from reading the docs that seems to be for query parameters only? And not as flexible as just hooking into existing serialization logic defined with Newtonsoft.Json (as `QuerySerializationMethod.Serialize` does).

**Comment by canton7** [comment]
> EnumMemberAttribute is not part of Newtonsoft.Json, it's in the .NET Framework/Core/Standard.

That's a fair point.

> Would it be a lot of work to add the ability to specify a serialization method for path parameters akin to QuerySerializationMethod for query parameters?

It's a little bit of handle-turning but not overly complicated - just follow the approach which has been laid down for QuerySerializationMethod.

> You mentioned RequestQueryParamSerializer but from reading the docs that seems to be for query parameters only?

You're correct - looks like I confused myself.

**Comment by Sharparam** [comment]
> It's a little bit of handle-turning but not overly complicated - just follow the approach which has been laid down for QuerySerializationMethod.

I'll have a look around the code I guess and see what I can figure out. Would a PR for this be welcome?

**Comment by canton7** [comment]
Sure, I'd happily accept a PR which does this. I'm happy to look at it myself, but I'm afraid it might be a week or so until I get time.

**Comment by Sharparam** [comment]
I've added some code in a fork to test this, but running into some code generation problems.

Unit tests for the path properties are throwing `InvalidProgramException`, the only change I've done in the code generation is to [emit a new int value for the path serialization enum](https://github.com/Sharparam/RestEase/blob/feature/path-serialization/src/RestEase/Implementation/ImplementationBuilder.cs#L549).

Comparing the emit calls to the one for query properties, I don't see any major differences, but I don't have much experience in IL code generation so. Do you have any ideas?

I also realized something while implementing this: A custom object that is serialized into a JSON string with the default json.net serializer would appear as `"value"` in the URL path, which is probably not what is desired.

The same happens when serializing a query parameter though. So I guess that should be handled by the consumer defining a custom serializer to handle that.

**Comment by canton7** [comment]
I think the issue is that you've changed the signatures for both `AddPathProperty` and `AddPathParameter`, but only updated the IL for `AddPathProperty`. That means it's probably falling over when it's trying to call `AddPathParameter`, since the serialization method isn't on the stack?

I'm not sure that having a JSON serializer for path parameters makes sense. For query parameters, sure, I've genuinely seen APIs which put url-encoded JSON there. But I've never seen that for a path.

I'm inclined to think that we should provide a serializer which just looks at EnumMemberAttribute / DisplayAttribute, but I'm in two minds as to whether it should be set by default. The problem here is backwards compatibility - once someone's opted into a particular serializer, we can't change it without breaking it. That means we can't add any functionality to a serializer after it's shipped, and we can't *change* what the default serializer is either. I don't want to get locked into a situation where we ship a default serializer that it turns out isn't quite what people want, and we can't change the serializer, or change to another default serializer.

**Comment by Sharparam** [comment]
Adding an EnumMemberSerializer would maybe be optimal yeah. It shouldn't need to be set as the default, it could default to `ToString` behaviour just like query parameter serialization does? And if `Serialized` is specified it will use the EnumMemberAttribute serializer, or a custom one if overridden in the `RestClient` properties.

**Comment by canton7** [comment]
Even setting the EnumMemberSerializer as the default serializer at all is a worry (even granted that the user has to change the serialization method). My concern is that, if we find out that EnumMemberSerializer is imperfect and we need to create a better version, we can't set the better version as the default serializer without breaking people.

I think I'd rather leave the default as null (so people get an exception if they try and seralizer without a serializer set), and document the steps people need to do to use the EnumMemberSerializer. To be honest, "use a couple of attributes on enums" feels like a weird default way to serialize path parameters as a whole (which can be any data type).

**Comment by Sharparam** [comment]
Honestly, as long as I can set a serializer in some way, I'm happy :)

Whether `Serialized` will default to something or be null and require setting a value manually, it will work for my usecase.

And as you say, it could be weird to automatically make `Serialized` use something that is intended for enums (unless it also looks at `DisplayAttribute`? but still pretty situational).

**Comment by canton7** [comment]
Implemented, thanks @Sharparam!
